name: sim
channels:
  - conda-forge
dependencies:
  - jupyter-book=1.*
  - jupyterlab=4.5.6
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.10.8
  - numpy=2.4.2
  - pandas=2.3.3
  - pip=26.0.1
  - plotly=6.5.0
  - python=3.12
  - scipy=1.17.1
  - simpy=4.1.1
  - pip:
    - ciw==3.2.7
    - streamlit
    - sim-tools==1.0.3
    - treat-sim==3.0.0
    
